#Itransformer.es is an online application to transform images
#Copyright (C) 2013  Manolo Salsas

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as
#published by the Free Software Foundation, either version 3 of the
#License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.

#You should have received a copy of the GNU Affero General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

#Contact: manolez@gmail.com - http://msalsas.com


imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: "@MSDHomeBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false 
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css: 
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
           jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
#closure:
#    jar: "%kernel.root_dir%/Resources/java/compiler.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
         translatable:
              type: annotation
              alias: Gedmo
              prefix: Gedmo\Translatable\Entity
              dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
         loggable:
              type: annotation
              alias: Gedmo
              prefix: Gedmo\Loggable\Entity
              dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
         tree:
              type: annotation
              alias: Gedmo
              prefix: Gedmo\Tree\Entity
              dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
         sluggable:
              type: annotation
              alias: Gedmo
              prefix: Gedmo\Sluggable\Entity
              dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: MSD\ForoBundle\Entity\User

herzult_forum:
    db_driver:          orm     # can be either "orm" or "odm"
    class:
        model:
            category:   MSD\ForoBundle\Entity\Category
            topic:      MSD\ForoBundle\Entity\Topic
            post:       MSD\ForoBundle\Entity\Post
        blamer:
            topic: MSD\ForoBundle\Blamer\TopicBlamer
            post:   MSD\ForoBundle\Blamer\PostBlamer
            
# Translations configuration

jms_i18n_routing:
    default_locale: %locale%
    locales: [en, de, fr, es]
    strategy: prefix_except_default

