#Itransformer.es is an online application to transform images
#Copyright (C) 2013  Manolo Salsas

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as
#published by the Free Software Foundation, either version 3 of the
#License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.

#You should have received a copy of the GNU Affero General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

#Contact: manolez@gmail.com - http://msalsas.com

msd_home_homepage:
    pattern:  /
    defaults: { _controller: MSDHomeBundle:Home:index }

msd_home_acercade:
    pattern:  /acercade
    defaults: { _controller: MSDHomeBundle:Home:acercade }
    
msd_home_verimagen:
    pattern: /verimagen
    defaults: { _controller: MSDHomeBundle:Home:verimagen}

msd_home_verImagenMuestra:
    pattern: /verImagenMuestra
    defaults: { _controller: MSDHomeBundle:Home:verImagenMuestra}
    
msd_home_submit:
    pattern:  /submit
    defaults: { _controller: MSDHomeBundle:Home:submit }

msd_home_vercambios:
    pattern: /vercambios
    defaults: { _controller: MSDHomeBundle:Home:vercambios }	

msd_home_cambiardimensiones:
    pattern: /cambiardimensiones
    defaults: { _controller: MSDHomeBundle:Home:cambiardimensiones }
    
msd_home_recortar:
    pattern: /recortar
    defaults: { _controller: MSDHomeBundle:Home:recortar }
    
msd_home_cambiarbrillo:
    pattern: /cambiarbrillo
    defaults: { _controller: MSDHomeBundle:Home:cambiarbrillo }
    
msd_home_cambiarcontraste:
    pattern: /cambiarcontraste
    defaults: { _controller: MSDHomeBundle:Home:cambiarcontraste }
    
msd_home_rotar:
    pattern: /rotar
    defaults: { _controller: MSDHomeBundle:Home:rotar }
    
msd_home_cambiaragrises:
    pattern: /cambiaragrises
    defaults: { _controller: MSDHomeBundle:Home:cambiaragrises }
    
msd_home_cambiaranegativo:
    pattern: /cambiaranegativo
    defaults: { _controller: MSDHomeBundle:Home:cambiaranegativo }
    
msd_home_resaltarbordes:
    pattern: /resaltarbordes
    defaults: { _controller: MSDHomeBundle:Home:resaltarbordes }
    
msd_home_resaltarrelieve:
    pattern: /resaltarrelieve
    defaults: { _controller: MSDHomeBundle:Home:resaltarrelieve }
    
msd_home_eliminacionmedia:
    pattern: /eliminacionmedia
    defaults: { _controller: MSDHomeBundle:Home:eliminacionmedia }
    
msd_home_borroso:
    pattern: /borroso
    defaults: { _controller: MSDHomeBundle:Home:borroso }

msd_home_borrosogauss:
    pattern: /borrosogauss
    defaults: { _controller: MSDHomeBundle:Home:borrosogauss }

msd_home_suavizado:
    pattern: /suavizado
    defaults: { _controller: MSDHomeBundle:Home:suavizado }

msd_home_pixelacion:
    pattern: /pixelacion
    defaults: { _controller: MSDHomeBundle:Home:pixelacion }

msd_home_convolucion:
    pattern: /convolucion
    defaults: { _controller: MSDHomeBundle:Home:convolucion }

msd_home_correcciongamma:
    pattern: /correcciongamma
    defaults: { _controller: MSDHomeBundle:Home:correcciongamma }

msd_home_colorear:
    pattern: /colorear
    defaults: { _controller: MSDHomeBundle:Home:colorear }

msd_home_resaltarcolores:
    pattern: /resaltarcolores
    defaults: { _controller: MSDHomeBundle:Home:resaltarcolores }

msd_home_atenuarcolores:
    pattern: /atenuarcolores
    defaults: { _controller: MSDHomeBundle:Home:atenuarcolores }

msd_home_lapizsuperfino:
    pattern: /lapizsuperfino
    defaults: { _controller: MSDHomeBundle:Home:lapizsuperfino }

msd_home_lapizfino:
    pattern: /lapizfino
    defaults: { _controller: MSDHomeBundle:Home:lapizfino }

msd_home_lapiznormal:
    pattern: /lapiznormal
    defaults: { _controller: MSDHomeBundle:Home:lapiznormal }

msd_home_lapizgrueso:
    pattern: /lapizgrueso
    defaults: { _controller: MSDHomeBundle:Home:lapizgrueso }

msd_home_efectopintura:
    pattern: /efectopintura
    defaults: { _controller: MSDHomeBundle:Home:efectopintura }

msd_home_efectoChe:
    pattern: /efectoChe
    defaults: { _controller: MSDHomeBundle:Home:efectoChe }

msd_home_papelarrugado:
    pattern: /papelarrugado
    defaults: { _controller: MSDHomeBundle:Home:papelarrugado }

msd_home_antiguo:
    pattern: /antiguo
    defaults: { _controller: MSDHomeBundle:Home:antiguo }

msd_home_fuego:
    pattern: /fuego
    defaults: { _controller: MSDHomeBundle:Home:fuego }

msd_home_gotas:
    pattern: /gotas
    defaults: { _controller: MSDHomeBundle:Home:gotas }

msd_home_luces:
    pattern: /luces
    defaults: { _controller: MSDHomeBundle:Home:luces }

msd_home_colores:
    pattern: /colores
    defaults: { _controller: MSDHomeBundle:Home:colores }

msd_home_molon:
    pattern: /molon
    defaults: { _controller: MSDHomeBundle:Home:molon }

msd_home_marcohorizontal:
    pattern: /marcohorizontal
    defaults: { _controller: MSDHomeBundle:Home:marcohorizontal }

msd_home_marcovertical:
    pattern: /marcovertical
    defaults: { _controller: MSDHomeBundle:Home:marcovertical }

msd_home_borrar:
    pattern: /borrar
    defaults: { _controller: MSDHomeBundle:Home:borrar }
    
msd_home_atras:
    pattern: /atras
    defaults: { _controller: MSDHomeBundle:Home:atras }
    
msd_home_guardar:
    pattern: /guardar
    defaults: { _controller: MSDHomeBundle:Home:guardar }
